# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0484ae1c68f8d072fce617e42ce71930c02e4da3e2326ba9e4fce7d5de1fffcbbbfb35cf3cc51aa128a73dd5b18a01a4d5f069b38040357dbcd00463ff18a713

test:
  secret_key_base: 47b166788bb64c4f276b085f36d98d580a840295071de103dfaa319f41d846c2ac379097f8688a71eb3905fd7c1fd5d4baaecf3d18fc78a83de367ea8bd2f4d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
